"""Add name column to product table

Revision ID: 7a53d978ee29
Revises: 
Create Date: 2025-06-19 19:25:58.346350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a53d978ee29'
down_revision = None
branch_labels = None
depends_on = None


# 修改後的 upgrade() 函式
def upgrade():
    with op.batch_alter_table('product', schema=None) as batch_op:
        # 步驟a：新增欄位，但暫時允許為空
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))

    # 步驟b：為所有舊資料填上預設值
    op.execute("UPDATE product SET name = '未命名商品' WHERE name IS NULL")

    with op.batch_alter_table('product', schema=None) as batch_op:
        # 步驟c：將欄位規則改回不允許為空
        batch_op.alter_column('name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('order')
    # ### end Alembic commands ###
